#!/usr/bin/env bun
/**
 * Bundle the dataset into a single TS module so the Cloudflare Worker can serve it without
 * filesystem access. Run before `wrangler deploy`.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { loadDatasetFromDir } from "@cosmsg/core";

const HERE = dirname(fileURLToPath(import.meta.url));
const DATA_DIR =
  process.env.COSMSG_DATA_DIR ?? join(HERE, "..", "..", "..", "data");
const OUT = join(HERE, "..", "src", "bundle.generated.ts");

const dataset = loadDatasetFromDir(DATA_DIR);
await mkdir(dirname(OUT), { recursive: true });
await writeFile(
  OUT,
  `// AUTO-GENERATED by scripts/gen-bundle.ts — do not edit.\n` +
    `import type { Dataset } from "@cosmsg/core";\n` +
    `export const dataset: Dataset = ${JSON.stringify(dataset)} as unknown as Dataset;\n`,
);
console.log(
  `Wrote ${OUT} (${dataset.index.chains.length} chains, ${
    (await import("node:fs")).statSync(OUT).size
  } bytes).`,
);
